version: '3.8'

services:
  # API Node.js
  api:
    build: .
    container_name: api
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
      - redis

  # Banco de dados PostgreSQL
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  # n8n
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${PGDATABASE}
      - DB_POSTGRESDB_USER=${PGUSER}
      - DB_POSTGRESDB_PASSWORD=${PGPASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - WEBHOOK_URL=https://n8n.personal-dev.online/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_LOG_LEVEL=debug
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - db
      - redis

  # WAHA (WhatsApp HTTP API)
  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    ports:
      - "3000:3000"
    environment:
      - WHATSAPP_HOOK_URL=https://n8n.personal-dev.online/webhook/whatsapp-mensagem
      - WHATSAPP_HOOK_EVENTS=message
      - WAHA_API_KEY=${WAHA_API_KEY}
    volumes:
      - waha_sessions:/app/.sessions
    depends_on:
      - n8n

volumes:
  pgdata:
  redisdata:
  n8n_data:
  waha_sessions:
